kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
  - name: test
    image: rust:1.69.0
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
      - cargo build
      - cargo test
